services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: 1000
        GID: 1000
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    command: hugo server --bind 0.0.0.0
