baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My presentations'
theme = 'reveal-hugo'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
